lurk-lab/YatimaStdLib.lean

YatimaStdLib/Algebra/Defs.lean, YatimaStdLib/Either.lean, YatimaStdLib/Foldable.lean, YatimaStdLib/List.lean, YatimaStdLib/RWST.lean, lakefile.lean
The cost of building mathlib all the time in each downstream dependency is a bit too cumbersome to deal with for now. If we ever find ourselves needing many many mathlib tools, we can always add this back.
I ported over a mellowed-out version of mathlib's `Monoids`. It is overly complicated for our current needs, but I think we should at least stay close to the true mathlib implementation for ease of future refactors.
=> Deprecate `mathlib`

YatimaStdLib/Identity.lean
If we have 
```lean
@[inline] instance idToA : Coe (Identity A) A where
coe a := a.runIdentity
```
then `#check ((1 : Nat) : Option Nat)` doesn't work. This is probably due to typeclass resolution being stuck in a `A -> Id A -> A ...` cycle. 
Removing the instance fixes this issue. I think it is worth it as breaking all of the implicit `a -> some a` coercions is disruptive (for example the `Cli` lib relies on it).
=> Remove the coe from `id A` to `A`

lean-toolchain
We want to generate and host our documentation using `doc-gen4` which requires a toolchain bump compatible with the latest DocGen4 commits.
=> Bumps toolchain to nightly-2022-08-09 

YatimaStdLib/NonEmpty.lean
We can now write `⟦1,2,3,4,5⟧` to generate non-empty lists!
=> Add notation for NEList

YatimaStdLib.lean, YatimaStdLib/Int.lean, YatimaStdLib/Zmod.lean
In Poseidon.lean and Nova.lean, we use modular arithmetic quite extensively. I'm gonna migrate our definitions to YatimaStdLib in order to avoid repetitions in those libraries.
=> Draft: Introducing modular arithmetic

YatimaStdLib/Polynomial.lean
A minor refactoring. The `ofnat` name is never used, but it might be problematic in declaring instances
=> Remove `ofnat` from the OfNat A 0 declaration

YatimaStdLib/Zmod.lean
The notation introduced in the Zmod file was conflicting with the usual arithmetic operations `+`, `*`, and `-` for the natural numbers.
Just get rid of it for now.
=> Remove Zmod notation

YatimaStdLib/Cached.lean
Problem: `Cached` ultimately represents a singleton value, and so two values of `Cached` of the same type must be equal to each other. It'd be nice for the simplifier to be able to use that. We've had a small theorem but forgot to put it in.
Solution: added the `@[simp]` theorem back.
=> Add Subsingleton equality theorem for simp

YatimaStdLib/ByteArray.lean, YatimaStdLib/List.lean
Problem: recently, a Bit inductive was introduced in YatimaStdLib. We define the same inductive in the Straume library, so currently there is code duplication.
Solution: moved some utilities we need to ByteArray.lean. This will allow us to refactor Straume to rely on YatimaStdLib more.
=> Move Bit utilities from Straume

YatimaStdLib/Bit.lean, YatimaStdLib/ByteArray.lean, YatimaStdLib/Float.lean, YatimaStdLib/Nat.lean, YatimaStdLib/NonEmpty.lean, YatimaStdLib/UInt.lean
A recent merged PR added a few methods from the `Poseidon.lean` repository, but did not preserve the namespaces. This PR fixes the namespace issue, and re-organizes slightly the dependencies between `Bit`, `ByteArray`, and `UInt`
=> Fix namespaces

YatimaStdLib/RBMap.lean
Problem: we need to use RBMap in Megaparsec, simulating finite computable sets through RBMap with Unit as nominal values. For ease of use, we need a way to construct such a map from just a list of keys, i.e. real values, as well as extract keys and merge and append two such "sets".
Solution: added these functions to RBMap module. Also deleted the Inhabited instance for RBMap as the same definition is present in Lean's stdlib.
=> Add some RBMap utilities

YatimaStdLib/Either.lean
In the Rust version of Nova, most of the functions return `Result`, a type the analogue of which is called `Either` in Haskell and other functional languages. For some cases, it's convenient to think of `Either` as a monad, so this PR introduces a Haskell-inspired monad instance for `Either`.
=> Monad instance for either

.gitignore, YatimaStdLib/AbstractMatrix.lean, YatimaStdLib/HashMap.lean, YatimaStdLib/HashSet.lean, YatimaStdLib/RBMap.lean, YatimaStdLib/RBNode.lean, YatimaStdLib/StringInterner/Interner.lean, lakefile.lean, lean-toolchain, lean_packages/manifest.json
Noteworthy changes:
* Added `std4` as a dependency
* Migrated from `Lean.RBMap` to `Std.RBMap`
* Change reference of `Lean.RBTree` to `Std.RBSet`
* Eliminated `RBMap.keys` and `RBMap.values` in favor of the Lean versions (and `.toArray` methods)
* Left `Lean.RBNode` for now
* Left `Lean.HashSet` for now (because `Std.HashSet` isn't implemented yet)
=> Bump toolchain to 2022-10-27

YatimaStdLib/Either.lean
It seems we're going to have a couple of pieces of code when the `Either` value might occur within another monad. For this purpose, I introduce the `ExceptT` monad transformer
=> Either transformer

YatimaStdLib/Cronos.lean
This PR moves Cronos from the `yatima-lang` to YatimaStdLib to allow for profiling in our other repos.
The only change is the increase of resolution by changing `IO.monoMsNow` to `IO.monoNanosNow`.
=> Move Cronos

YatimaStdLib/GaloisField.lean, YatimaStdLib/Zmod.lean
The moved `GaloisField` file is very close to the file found in the Nova repository, but there were a few additions and deletions in the transfer to make working with Galois Fields more ergonomic.
=> Move Galois Field from Nova

Tests/Nat.lean, YatimaStdLib/Nat.lean, YatimaStdLib/USize.lean
I've just realised that nextPowerOfTwo defined for natural number is slightly more helpful for Nova
=> Rewrite nextPowerOfTwo in terms of Nat

YatimaStdLib/Ring.lean
Actually, we can embed integers to an arbitrary ring uniquely, here's the version of that fact formulated for natural numbers that would allow reducing the number of constrains in Nova
=> Nat To Ring coercion

Tests/LightData.lean, YatimaStdLib/DataClasses.lean, YatimaStdLib/LightData.lean
This PR adds two typeclasses:
* `HashRepr` to generalize data formats that have hashing functions and that have inner representations for their hashes
* `Encodable` to generalize conversion interfaces between datatypes
These are the basic needs from any data format that we want to use on `yatima-lang`
=> Add `DataClasses.lean` and enhance `LightData`

YatimaStdLib/Ring.lean
It's auto generated by Lean already (via `extends`)
=> Remove Ring instance

YatimaStdLib/List.lean, YatimaStdLib/NonEmpty.lean, YatimaStdLib/Traversable.lean
Previously defined `NEList` was inefficient because conversions between `NEList` and `List`, whichever way, were O(n). With this new definition, conversions will be O(1). In fact, an `NEList` will have the same memory layout as a `List`, so if the compiler is smart enough the conversion will be 0 cost. There's also an added benefit of being able to reuse functions on `List` when defining their `NEList` counterpart, leading to more concise code.
=> Better definition of `NEList`

Tests/Int.lean, YatimaStdLib/Bit.lean, YatimaStdLib/Int.lean, YatimaStdLib/Nat.lean, lakefile.lean
Problem: for Wasm.lean, we need some bithwise arithmetics for `Int`s. Lean's stdlib has those for `Nat`s, but surprisingly not for Ints.
Solution: implemented bitwise AND, OR, and XOR for Ints, as well as left and right shifts. Defined relevant instances. Also added twos complement for Bits.
Wrote relevant tests on Ints.
=> Add some `Int` bitwise arithmetics

YatimaStdLib/Ring.lean
I wasn't totally successful in troubleshooting the issues I was running into, but deleting these instances fixed everything.
I think maybe we should just expect to write an `OfNat` instance by hand for any type instantiating `Ring` going forward. 
(besides, the `Ring.fromNat` function was terribly slow if someone had to use it and didn't implement their own `OfNat` instance)
=> Remove Nat to Ring coercions 

YatimaStdLib/Ring.lean
It's convenient to negate ring elements sometimes, so here's the instance of `Neg`
=> Neg instance for Ring

YatimaStdLib/NonEmpty.lean
The `data/ne` version of `NEList` has a huge issue: it cannot be nested inside another inductive. That's why I'm redefining it as a `head/tail` list again. This change should not conflict with anything else, except if it is using an explicit pattern match to extract either `data` or `ne`
=> Redefined NEList again

lake-manifest.json, lakefile.lean, lean-toolchain
Check over the lakefile pretty carefully:
1) I updated the FFI target (since the old API seems to have been removed?)
2) I changed the dependencies to target `main` instead of specific commits now that `lake-manifest` has gotten pretty robust. Let me know if I should revert this change.
=> bump toolchain to stable
